<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <AssemblyName>Klick</AssemblyName>
    <RootNamespace>Klick</RootNamespace>

    <!-- 单文件发布：Deck 目录扔一个 exe 直接双击启动 (⁎⁍̴̛ᴗ⁍̴̛⁎) -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <IncludeNativeContentInSingleFile>true</IncludeNativeContentInSingleFile>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="app.png" />
  </ItemGroup>

</Project>
